### ISSUE TITLE
How to set up Multilevel, Sublevel and Levelgraph?

### ISSUE THREAD

**Issue by Industrial** [levelgraph/levelgraph#109]
Hi. I would like to start to use Levelgraph as the triple store to eventually back a webapp and take over functionality from MongoDB.

For it to do that I would need to have Levelgraph running as a network server. I'm not too worried about scale now so running just 1 Levelgraph node would be fine. Luckily there is [Multilevel](https://github.com/juliangruber/multilevel) to do this.

1) Right now, when I configure a sublevel of multilevel to be a levelgraph and write the manifest file and then use that manifest in a client, I can't seem to use the levelgraph API of the sublevel.

2) Levelgraph is basically one graph, where I see other triple store software support multiple graphs. I guess this may be achieved by using Lublevel. When I use Multilevel for exposing multiple leveldb's, does that mean that the RPC client will be able to create new sublevels in the multilevel database server and choose for a newly created sublevel to become a levelgraph server?

**Comment by Industrial** [comment]
Instead of using Multilevel, I have tried using Dnode and a net.Server to serve the Levelgraph API over RPC. This works for all the asynchronous methods but for all the synchronous methods like .getStream() won't work since Dnode doesn't seem to support it :S.

I would love to have remote access (RPC) to a db server and actually create/change the db structure around..

**Comment by Industrial** [comment]
Even when I wrap the synchronous methods like

```javascript
var interface = {
  getStream: function(args..., cb) {cb(null, levelDB.getStream(args...));}
};
```

it won't work, since Dnode doesn't support event emitters or streams.

**Comment by snowyu** [comment]
`levelgraph` is not a levelup database. It uses the levelup database as backend.
It is hard to let the levelgraph use the same API with levelup database.
the levelup key/value database processes the key and the value only.
the graph database processes the vertex(subject, object) and arc(predicate).

you need learn more how to dnode transfer the stream. maybe this [RpcStream](https://github.com/dominictarr/rpc-stream) is a good start.

**Comment by mcollina** [comment]
There are two possible ways for dealing with MultiLevel. The first one is just to forget about LevelGraph, and use multilevel to forward a LevelDB database. This approach works fine, but it will be slow if you do _complex joins_. The other option is finishing #60, if you want give it a spin.
