### ISSUE TITLE
Crashes when using sublevel on approximateSize

### ISSUE THREAD

**Issue by djiworks** [levelgraph/levelgraph#132]
Hi,

When I used your library with sublevel I got a crash concerning approximateSize when calling the `search` method.
I found closed issues referring to this: (https://github.com/mcollina/levelgraph/issues/87, https://github.com/mcollina/levelgraph/issues/78).

But the versions are different:

```
    "levelup": "0.19.0",
    "level-sublevel": "^6.4.6",
    "levelgraph": "^1.0.0"
```

Error:
.../node_modules/levelgraph/lib/queryplanner.js:51
      if (db.db.approximateSize) {
               ^
TypeError: Cannot read property 'approximateSize' of undefined
    at async.each.result.forEach.q.stream (..../node_modules/levelgraph/lib/queryplanner.js:51:16)
    at .../node_modules/levelgraph/node_modules/async/lib/async.js:162:20
    at .../node_modules/levelgraph/node_modules/async/lib/async.js:230:13
    at _arrayEach (.../node_modules/levelgraph/node_modules/async/lib/async.js:81:9)
    at _each (.../node_modules/levelgraph/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (.../node_modules/levelgraph/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (.../node_modules/levelgraph/node_modules/async/lib/async.js:206:22)
    at planner (.../node_modules/levelgraph/lib/queryplanner.js:47:11)
    at Object.searchStream (.../node_modules/levelgraph/lib/levelgraph.js:130:5)
    at Object.search (.../node_modules/levelgraph/lib/utilities.js:46:27)

Actually, the given fast hack in #87 still works.

**Comment by mcollina** [comment]
Would you like to submit a PR to fix this behavior? ApproximateSize was
moved in leveldown. I think the best route is to try to find the leveldown
from a sublevel.
Il giorno dom 30 ago 2015 alle 15:23 Djothi Grondin <
notifications@github.com> ha scritto:

**Comment by djiworks** [comment]
I read your code about queryplanner.js, and I thought that the use of db.db.approximateSize will simply return the size of the global db not the size of the partitionned one. So, I firstly wanted to force your code to pass by your else statement doing (avoiding the approximateSize of levelup) : 
```
db = sublevel(levelup("yourdb"));
subDb = db.sublevel('graph')
subDb.db = {} // Just to fix the 'approximateSize' of undefined
graph = levelgraph(subDb, options);
```
Did I correctly understand your code about l51 - l62 (queryplanner.js) ?

Then, I focused on sublevel source code following your comment. But I'm not really sure we can find back the leveldown from sublevel.

I may need more explanation to make the PR. Actually, I'm not sure that this bug is due to your lib but from sublevel. Or a simple check on db.db existence could do the job.

What do you think ?

**Comment by mcollina** [comment]
Definitely, thansk!
