### ISSUE TITLE
Tree Traversal & Querying

### ISSUE THREAD

**Issue by ohenepee** [levelgraph/levelgraph#170]
I'm evaluating levelgraph for my project in which the main database is a tree (more like a family tree) with this structure
`1 parent -> 2 children -> each child will also have 2 children -> ...on and on...`

I wanted to know how to query such a graph using levelgraph to fetch all members say from `2nd generation/level deep` to `4th generation/level deep`?

**Comment by mattcollier** [comment]
Does this address your issue?  https://github.com/levelgraph/levelgraph#limit-and-offset-1

**Comment by mattcollier** [comment]
No, it does not, `limit` and `offset` operate on the *results* of the search, not as criteria for the search.

**Comment by ohenepee** [comment]
I guess I'll have to look elsewhere then. Thanks
