### ISSUE TITLE
Triple identifiers

### ISSUE THREAD

**Issue by JWorthington** [levelgraph/levelgraph#180]
Can you store an identifier for a triple? You have a property field for each triple, but can I retrieve a triple by its property alone?

**Comment by BigBlueHat** [comment]
We don't yet support Named Graphs, but there has been some work done on it. See #43 and https://github.com/levelgraph/levelgraph-jsonld/issues/43 for more on the topic.

There's also some preliminary work done in https://github.com/levelgraph/levelgraph-jsonld/tree/feature/named-graphs if you want to explore it more.

In the meantime, keeping a property on each triple and storing the name of the graph there and then using that to filter down to the graph you're looking for, is probably the best option atm.
